---
- name: Install Apache Web Server
  hosts: 192.168.1.131
  become: yes
  remote_user: sloba
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

